/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fees_management_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import static javax.swing.UIManager.getInt;



/**
 *
 * @author Pratik
 */
public class SignUp extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SignUp.class.getName());

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }
    
    int getId() {
    int id = 0;
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        String url = "jdbc:mysql://localhost:3306/csfmsdatabase?zeroDateTimeBehavior=CONVERT_TO_NULL";
        Connection con = DriverManager.getConnection(url,"root","Pratik@123");

        String sql = "SELECT MAX(id) FROM signup";
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(sql);

        if (rs.next()) {
            id = rs.getInt(1);   // max(id)
        }
        id = id + 1; // next id
    } catch(Exception e) {
        e.printStackTrace();
    }
    return id;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtcnumber = new javax.swing.JTextField();
        txtfname = new javax.swing.JTextField();
        txtlname = new javax.swing.JTextField();
        txtuname = new javax.swing.JTextField();
        txtconfirmpass = new javax.swing.JPasswordField();
        txtpass = new javax.swing.JPasswordField();
        txtdob = new com.toedter.calendar.JDateChooser();
        btnlogin = new javax.swing.JButton();
        btnsignup = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        labelcnumbererror = new javax.swing.JLabel();
        labelpasserror = new javax.swing.JLabel();
        labelcpasserror1 = new javax.swing.JLabel();
        firstnameerror = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Sign Up");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(318, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 110));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 153));
        jLabel2.setText("Contact Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 150, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 153));
        jLabel3.setText("First Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 100, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 153));
        jLabel4.setText("Last Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 100, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 153));
        jLabel5.setText("Username");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 100, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 153));
        jLabel6.setText("Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 100, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 153));
        jLabel7.setText("Confirm Password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 170, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 0, 153));
        jLabel8.setText("D. O. B.");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 100, -1));

        txtcnumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtcnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcnumberActionPerformed(evt);
            }
        });
        txtcnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcnumberKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcnumberKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcnumberKeyTyped(evt);
            }
        });
        getContentPane().add(txtcnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 140, -1));

        txtfname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfnameActionPerformed(evt);
            }
        });
        txtfname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfnameKeyPressed(evt);
            }
        });
        getContentPane().add(txtfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 140, -1));

        txtlname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtlname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtlname, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 140, -1));

        txtuname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtuname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtunameActionPerformed(evt);
            }
        });
        getContentPane().add(txtuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 140, -1));

        txtconfirmpass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtconfirmpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtconfirmpassActionPerformed(evt);
            }
        });
        txtconfirmpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtconfirmpassKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtconfirmpassKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtconfirmpassKeyTyped(evt);
            }
        });
        getContentPane().add(txtconfirmpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 140, 30));

        txtpass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassActionPerformed(evt);
            }
        });
        txtpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpassKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpassKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpassKeyTyped(evt);
            }
        });
        getContentPane().add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 140, 30));
        getContentPane().add(txtdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 140, 30));

        btnlogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnlogin.setText("Login");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, -1, -1));

        btnsignup.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnsignup.setText("Sign Up");
        btnsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignupActionPerformed(evt);
            }
        });
        getContentPane().add(btnsignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, -1, -1));

        btnclear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, -1, -1));

        labelcnumbererror.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelcnumbererror.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(labelcnumbererror, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 260, 20));

        labelpasserror.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelpasserror.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(labelpasserror, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 266, 260, 20));

        labelcpasserror1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelcpasserror1.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(labelcpasserror1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 260, 20));

        firstnameerror.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(firstnameerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 200, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcnumberActionPerformed

    private void txtfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfnameActionPerformed
        // TODO add your handling code here:
   
    }//GEN-LAST:event_txtfnameActionPerformed

    private void txtlnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlnameActionPerformed

    private void txtunameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtunameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtunameActionPerformed

    private void btnsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignupActionPerformed
validation();       
if(validation()){
    insertData();
}else{
    JOptionPane.showMessageDialog(this, "validation issue");
}
    }//GEN-LAST:event_btnsignupActionPerformed

    private void txtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassActionPerformed

    private void txtpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpassKeyPressed
        // TODO add your handling code here:
        passwordChecker();
    }//GEN-LAST:event_txtpassKeyPressed

    private void txtpassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpassKeyReleased
        // TODO add your handling code here:
        passwordChecker();
    }//GEN-LAST:event_txtpassKeyReleased

    private void txtpassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpassKeyTyped
        // TODO add your handling code here:
        passwordChecker();
    }//GEN-LAST:event_txtpassKeyTyped

    private void txtcnumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcnumberKeyPressed
        // TODO add your handling code here:
        mobileCheck();
    }//GEN-LAST:event_txtcnumberKeyPressed

    private void txtcnumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcnumberKeyReleased
        // TODO add your handling code here:
        mobileCheck();
    }//GEN-LAST:event_txtcnumberKeyReleased

    private void txtcnumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcnumberKeyTyped
        // TODO add your handling code here:
        mobileCheck();
    }//GEN-LAST:event_txtcnumberKeyTyped

    private void txtfnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfnameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfnameKeyPressed

    private void txtconfirmpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtconfirmpassActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtconfirmpassActionPerformed

    private void txtconfirmpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtconfirmpassKeyPressed
        // TODO add your handling code here:
      // confirmpassword();
    }//GEN-LAST:event_txtconfirmpassKeyPressed

    private void txtconfirmpassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtconfirmpassKeyReleased
        // TODO add your handling code here:
        //confirmpassword();
    }//GEN-LAST:event_txtconfirmpassKeyReleased

    private void txtconfirmpassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtconfirmpassKeyTyped
        // TODO add your handling code here:
        //confirmpassword();
    }//GEN-LAST:event_txtconfirmpassKeyTyped

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here:
        Login l1 = new Login();
        this.dispose();
        l1.setVisible(true);
    }//GEN-LAST:event_btnloginActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        txtfname.setText("");
        txtlname.setText("");
        txtuname.setText("");
        txtpass.setText("");
        txtconfirmpass.setText("");
        txtdob.setDate(null);
        txtcnumber.setText("");
            
    }//GEN-LAST:event_btnclearActionPerformed

    //memory
    String fname,lname,uname,password,cpassword,cnumber;
        Date dob;
        
        
        void insertData(){
            SimpleDateFormat s1= new SimpleDateFormat("yyyy-MM-dd");
           String dob1= s1.format(dob);
                    
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                String url = "jdbc:mysql://localhost:3306/csfmsdatabase?zeroDateTimeBehavior=CONVERT_TO_NULL";
                Connection con = DriverManager.getConnection(url,"root","Pratik@123");
                
                String sql="insert into signup values(?,?,?,?,?,?,?)";
                PreparedStatement st = con.prepareStatement(sql);
                
                st.setInt(1, getId());
                st.setString(2, fname);
                st.setString(3, lname);
                st.setString(4, uname);
                st.setString(5, password);
                st.setString(6, dob1);
                st.setString(7, cnumber);
               int i= st.executeUpdate();
                
               if(i>0){
                   JOptionPane.showMessageDialog(this,"Record Inserted successfully");
               }else{
                      JOptionPane.showMessageDialog(this,"Record Not Inserted successfully");
               }
               
                
                 
                
                
            }catch(Exception e){
                e.printStackTrace();
            }
        }
        
        boolean validation(){
            fname = txtfname.getText();
            lname = txtlname.getText();
            uname = txtuname.getText();
            password = txtpass.getText();
            cpassword = txtconfirmpass.getText();
            dob = txtdob.getDate();
            cnumber = txtcnumber.getText();
            
            if(fname.equals("")){
                JOptionPane.showMessageDialog(this,"please enter your first name...");
                return false;
            }
            if(lname.equals("")){
                JOptionPane.showMessageDialog(this,"please enter your last name...");
                return false;
            }
            if(uname.equals("")){
                JOptionPane.showMessageDialog(this,"please enter your username...");
                return false;
            }
            if(password.equals("")){
                JOptionPane.showMessageDialog(this,"please enter your password...");
                return false;
            }
            if(cpassword.equals("")){
                JOptionPane.showMessageDialog(this,"please enter your confirm password...");
                return false;
            }
            if(dob.equals(null)){
                JOptionPane.showMessageDialog(this,"please enter your D.O.B....");
                return false;
            }
            if(cnumber.equals("")){
                JOptionPane.showMessageDialog(this,"please enter your contact number...");
                return false;
            }
            return true;
        }
        
        void passwordChecker(){
             password = txtpass.getText();
             if(password.length()>=8){
                 labelpasserror.setText("");
             }else{
                 labelpasserror.setText("Enter 8 digit password..");
             }
        }
        
//        void confirmpassword(){
//            cpassword = txtconfirmpass.getText();
//            if(cpassword == passwordChecker()){
//                labelcpasserror1.setText("");
//            }else{
//                labelcpasserror1.setText("Enter same correct password");
//            }
//        }
        
        void mobileCheck(){
             cnumber = txtcnumber.getText();
             
             if(cnumber.length()==10){
                labelcnumbererror.setText("");
             }else{
                 labelcnumbererror.setText("Enter 10 digit contact number..");
             }
        }
        
    
        
        
        
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SignUp().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnsignup;
    private javax.swing.JLabel firstnameerror;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelcnumbererror;
    private javax.swing.JLabel labelcpasserror1;
    private javax.swing.JLabel labelpasserror;
    private javax.swing.JTextField txtcnumber;
    private javax.swing.JPasswordField txtconfirmpass;
    private com.toedter.calendar.JDateChooser txtdob;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtlname;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtuname;
    // End of variables declaration//GEN-END:variables
}
